App_Login/urls.py
from django.urls import path
from App_Login import views
from django.contrib.auth import views as auth_views

app_name = 'App_Login'

urlpatterns=[
    path('register/',views.register_attempt,name='register_attempt'),
    path('login/',views.login_attempt,name='login_attempt'),
    path('logout/',views.logout_user,name='logout'),
    path('change-password/',views.change_password,name='change-password'),
    path('subscriber_payment/',views.subscriber_payment,name='subscriber_payment'),
    path('token/',views.token_send,name='token_send'),
    path('success/',views.success,name='success'),
    path('verify/<auth_token>' , views.verify , name="verify"),
    path('error/' , views.error_page , name="error_page")
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)



]

Index/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.home,name='home'),
    path('demo',views.demo,name='demo'),
    path('demo1',views.demo1,name='demo1'),
    path('launch',views.launch,name='launch'),
    path('aboutus' , views.aboutus , name='aboutus'),
    path('brochure' , views.brochure , name='brochure'),
    path('membership' , views.membership , name='membership'),
    path('payment-status' , views.payment_status , name='payment_status'),
    path('l@123' , views.lobby , name='lobby'),
    path('e@123' , views.exhibition , name='exhibition'),
    path('a@123' , views.auditorium , name='auditorium'),
    path('c@123' , views.clubhouse , name='clubhouse'),
    path('n@123' , views.ninja , name='ninja'),
    path('t@123' , views.tic_tac_toe , name='tic-tac-toe'),
    path('p@123' , views.planet_defense , name='planet_defense'),
    path('s@123' , views.snake , name='snake'),
    path('se@123' , views.selfie , name='selfie'),
    path('d@123' , views.details , name='details'),
]

Indican/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Index.urls')),
    path('contactus/', include('contact.urls')),
    path('account/', include('App_Login.urls')),
    path('reset_password/',
    auth_views.PasswordResetView.as_view(template_name="registration/password_reset.html"),
    name="reset_password"),

   path('reset_password_sent/',
       auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_sent.html"),
       name="password_reset_done"),

   path('reset/<uidb64>/<token>/',
    auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_form.html"),
    name="password_reset_confirm"),

   path('reset_password_complete/',
       auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_done.html"),
       name="password_reset_complete"),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT})
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.contactus,name='contact'),

]

contact/models.py
from django.db import models

# Create your models here.
class contactlist(models.Model):
    address = models.TextField(max_length=800, blank=False)
    email = models.CharField(max_length=100, blank=False)
    phone = models.CharField(max_length=100, blank=False)
    def __str__(self):
        return self.email

class contactform(models.Model):
    name = models.CharField(max_length=100, blank=False)
    email = models.CharField(max_length=100, blank=False)
    subject = models.CharField(max_length=400, blank=False)
    message = models.TextField(max_length=800, blank=False)
    def __str__(self):
        return self.email

contact/views.py
from django.shortcuts import render
from .models import contactlist, contactform
from django.core.mail import send_mail
# Create your views here.
def contactus(request):
    # contactlistdata = contactlist.objects.all()[0]
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        send_mail(
            email ,
            message,
            name,
            ['info@indicanfc.com']
            )

        contactformdata = contactform(name=name, email=email, subject=subject, message=message)
        contactformdata.save()


    # context = {
    #     'contactlist':contactlistdata,
    # }
    return render(request,'contact.html', )

templates/brochure.html
{% extends 'layouts.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Brochure
{% endblock %}

{% block content %}
<div class="padding padding2">
  <div class="container">
    <center>
      <div class="download">
        <a href="{% static 'img/indican_brochure_2.pdf'%}" download><button type="button" class="btn btn-outline-warning download1">Download <i class="fas fa-download"></i></button></a>
      </div>
    <embed class="pdf"  type="application/pdf" src="{% static 'img/indican_brochure_2.pdf'%}" width="50%" height="600">
  </div>
</div>
{% endblock %}

templates/contact.html
{% extends 'layouts.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Contact Us
{% endblock %}

{% block content %}
<div class="padding padding3">
  <!-- ======= Contact Section ======= -->
  <section id="contact" class="contact">
    <div class="container" data-aos="fade-up">

      <div class="section-title">
        <h2>Contact</h2>
        <p>Contact Us</p>
      </div>
    </div>

    <!-- <div data-aos="fade-up">
      <iframe style="border:0; width: 100%; height: 350px;" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621" frameborder="0" allowfullscreen></iframe>
    </div> -->

    <div class="container" data-aos="fade-up">

      <div class="row mt-5">

        <div class="col-lg-4">
          <div class="info">
            <div class="address">
              <i class="bi bi-geo-alt"></i>
              <h4>Location:</h4>
              <p>Water Park Golf Club, 61174, Regional Road No. 27, Wainfleet, Welland ON.</p>
            </div>
            <br>
            <div class="address">
              <i class="bi bi-geo-alt"></i>
              <h4>Communication Address:</h4>
              <p>Gold Souk, Block-C, Sushant Lok, Phase-I, Sec-43, Gurgaon-122002, Haryana.<br><br>VRAKSH, E-6 Second Floor, Kalkaji Main Market, New Delhi-110019.</p>
            </div>

            <div class="email">

              <i class="bi bi-envelope"></i>
              <h4>Email:</h4>
              <a href="mailto:info@indicanfc.com"><p>info@indicanfc.com</p></a>
            </div>

            <div class="phone">
              <i class="bi bi-phone"></i>
              <h4>Call:</h4>
              <a href="tel:+917892650335"><p>+91 7303503302</p></a>
            </div>

          </div>

        </div>


        <div class="col-lg-8 mt-5 mt-lg-0">

          <form action="" method="POST" >
            {% csrf_token %}
            <div class="row">
              <div class="col-md-6 form-group">
                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
              </div>
              <div class="col-md-6 form-group mt-3 mt-md-0">
                <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
              </div>
            </div>
            <div class="form-group mt-3">
              <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
            </div>
            <div class="form-group mt-3">
              <textarea class="form-control" name="message" rows="8" placeholder="Message" required></textarea>
            </div>

            <div class="text-center"><button type="submit">Send Message</button></div>
          </form>

        </div>

      </div>

    </div>
  </section><!-- End Contact Section -->
</div>
{% endblock %}

templates/demo.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->

    <link href="{% static 'css/demo.css'%}" rel="stylesheet">
    <title>Hello, world!</title>
  </head>
  <body>

    <div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel" data-interval="2500">
      <div class="container2 ">
        <div class="row">
          <div class="col-lg-8 col-8">
            <h1>Welcome to <span>INDICAN FRIENDSHIP CLUB</span></h1>
            <h2></h2>

            <div class="btns">
              <a href="{% url 'App_Login:login_attempt' %}" class="btn-menu animated fadeInUp scrollto">Join Us</a>

            </div>

          </div>
          <div class="col-lg-4 col-4 d-flex align-items-center justify-content-center position-relative" data-aos="zoom-in" data-aos-delay="200">
            <a href="{% url 'launch' %} "class=" play-btn"></a>
          </div>

        </div>
      </div>
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="5"></li>
  </ol>
<div class="a">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block img w-100" src="{% static 'img/toronto1.jpg'%}" alt="First slide">

    </div>
    <div class="carousel-item">
      <img class="d-block img w-100" src="{% static 'img/taj-mahal1.jpg'%}" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block img w-100" src="{% static 'img/niagra1.jpg'%}" alt="Third slide">
    </div>
    <div class="carousel-item">
      <img class="d-block img w-100" src="{% static 'img/qutub-minar1.jpg'%}" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block img w-100" src="{% static 'img/hopewell1.jpg'%}" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block img w-100" src="{% static 'img/gateway-to-india1.jpg'%}" alt="Second slide">
    </div>
  </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/demo1.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->

    <link href="{% static 'css/demo.css'%}" rel="stylesheet">
    <title>Hello, world!</title>
  </head>
  <body>

    <div class="hero-slider" data-carousel>
  <div class="carousel-cell" style="background-image:url(https://78.media.tumblr.com/469798be38e86cc01ea4ba08563af785/tumblr_p38kazKBIX1snegd3o1_1280.jpg);">
    <div class="overlay"></div>
    <div class="slide-content">
      <div class="mask">
        <h2 class="title">Slide 1</h2>
      </div>
      <div class="divider"></div>
      <div class="mask">
        <p class="caption">Flickity is fun to use.</p>
        <a href="https://flickity.metafizzy.co/" target="_blank" class="btn">Tell me more</a>
      </div>
     </div>
  </div>
  <div class="carousel-cell" style="background-image:url(https://78.media.tumblr.com/f3577e640674f66119dad5ce61b4582c/tumblr_ozf8vw9LYN1snegd3o1_1280.jpg);">
    <div class="overlay"></div>
    <div class="slide-content">
      <div class="mask">
        <h2 class="title">Slide 2</h2>
      </div>
      <div class="divider"></div>
      <div class="mask">
        <p class="caption">Flickity is flexible.</p>
        <a href="https://flickity.metafizzy.co/" target="_blank" class="btn">Tell me more</a>
      </div>
     </div>
  </div>
  <div class="carousel-cell" style="background-image:url(https://78.media.tumblr.com/895918f98ebb3644e885f663bf63ba61/tumblr_pa4fmzV4kV1snegd3o1_1280.jpg);">
    <div class="overlay"></div>
    <div class="slide-content">
      <div class="mask">
        <h2 class="title">Slide 3</h2>
      </div>
      <div class="divider"></div>
      <div class="mask">
        <p class="caption">Flickity is awesome.</p>
        <a href="https://flickity.metafizzy.co/" target="_blank" class="btn">Tell me more</a>
      </div>
     </div>
  </div>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/exhibition.html
{% extends 'layouts1.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Exhibition
{% endblock %}
{% block style %}
<link href="{% static 'css/exhibition.css'%}" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="padding">
<img src="{% static 'img/graphic.jpg'%}" alt="">




</div>

{% endblock %}

templates/launch.html
{% load static %}
<html>
<head>
	<title>Launching Soon</title>
	<!-- ViewPort -->
  	<meta name="viewport" content="width=device-width, initial-scale=1">


  	<!-- JQUERY -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<!-- POPPER_JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

	<!-- Fontawesome -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/rotate.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style1.css'%}">
	<!-- Local CSS -->
  <link href="{% static 'css/launch.css'%}" rel="stylesheet">




</head>
<body>

	<div class="cursor"></div>
<!-- ======= Top Bar ======= -->
<div id="topbar" class="d-flex align-items-center fixed-top">
	<div class="container d-flex justify-content-center justify-content-md-between">

		<div class="contact-info d-flex align-items-center">
			<i class="bi bi-envelope d-flex align-items-center"><span>info@indicanfc.com</span></i>
		</div>


	</div>
</div>

<!-- ======= Header ======= -->
<header id="header" class="fixed-top d-flex align-items-cente">
  <div class="container-fluid container-xl d-flex align-items-center justify-content-lg-between">

    <h1 class="logo me-auto me-lg-0"><a href="{% url 'home' %}" class="logo me-auto me-lg-0"><img src="{% static 'img/logo5.png'%} " alt="" class="img-fluid"></a></h1>
    <!-- Uncomment below if you prefer to use an image logo -->


    <nav id="navbar" class="navbar order-last order-lg-0">
      <ul>
        <li><a class="nav-link scrollto" href="{% url 'home' %}">Home</a></li>
        <li><a class="nav-link scrollto" href="{% url 'aboutus' %}">About</a></li>
        <li><a class="nav-link scrollto" href="{% url 'brochure' %}">Brochure</a></li>
        <li><a class="nav-link scrollto" href="{% url 'membership' %}">Membership</a></li>
        <li><a class="nav-link scrollto" href="{% url 'contact' %}">Contact</a></li>

        {% if user.is_authenticated %}
        <li><a href="{% url 'App_Login:logout' %}">Logout</a></li>


        {% else %}
        <li><a href="{% url 'App_Login:login_attempt' %}">Login</a></li>

        {% endif %}

      </ul>
      <i class="bi bi-list mobile-nav-toggle"></i>
    </nav><!-- .navbar -->
    <a href="{% url 'launch' %}" class="book-a-table-btn scrollto d-none d-lg-flex">Watch Live</a>

  </div>
</header><!-- End Header -->

<center>

<div class="cover">
      </div>
      <div class="cover1">
        <div class="container d-flex flex-column align-items-center">


          <h2 class="title">
            <br>
      <span class="title-word title-word-1">Indican</span>
      <span class="title-word title-word-2">Friendship</span>
      <span class="title-word title-word-3">Club</span>

    </h2>
    <h1>Stay tuned for something amazing!!</h1>





      <div class="countdown d-flex justify-content-center" data-count="2022/02/06">
        <div>
          <h3>%d</h3>
          <h4>Days</h4>
        </div>
        <div>
          <h3>%h</h3>
          <h4>Hours</h4>
        </div>
        <div>
          <h3>%m</h3>
          <h4>Minutes</h4>
        </div>
        <div>
          <h3>%s</h3>
          <h4>Seconds</h4>
        </div>
      </div>
      <div class="container1">
        <div class="headline">

        </div>
        <div class="social-buttons">
        <!-- facebook  Button -->
                <a href="https://www.facebook.com/Indican-Friendship-Club-110939114779952" target="blank" class="social-margin">
                  <div class="social-icon facebook">
                    <i class="fa fa-facebook" aria-hidden="true"></i>
                  </div>
                </a>



                <!-- Youtube Button -->
                <a href="https://www.youtube.com/channel/UCwzFcdmQdyONzEkkrRO-_pQ" target="blank"  class="social-margin">
                  <div class="social-icon youtube">
                    <i class="fa fa-youtube" aria-hidden="true"></i>
                  </div>
                </a>

                <a href="https://instagram.com/indicanfc?utm_medium=copy_link" target="blank" class="social-margin">
                  <div class="social-icon instagram">
                    <i class="fa fa-instagram" aria-hidden="true"></i>
                  </div>
                </a>

          <!-- TwitterButton -->
                <a href="https://twitter.com/indicanfc" target="blank" class="social-margin">
                  <div class="social-icon twitter">
                    <i class="fa fa-twitter" aria-hidden="true"></i>
                  </div>
                </a>
        </div>
        </div>

        <!-- <form action="forms/notify.php" method="post" role="form" class="php-email-form">
          <div class="subscribe-form">
            <input type="email" name="email"><input type="submit" value="Subscribe">
          </div>
          <div class="mt-2">
            <div class="loading">Loading</div>
            <div class="error-message"></div>
            <div class="sent-message">Your notification request was sent. Thank you!</div>
          </div>
        </form> -->
      </div>

      </div>
</center>

</body>

</html>
<script src="{% static 'js/launch.js'%} "></script>
<script src="{% static 'js/rotate.js'%}"></script>
<script src="{% static 'js/main1.js'%}" type="text/javascript"></script>

templates/layouts1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title%}

    {% endblock %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'img/logo3.png'%}" rel="icon">
  <link href="{% static 'img/logo3.png'%} " rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link href="{% static 'fontawesome_free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/webcamjs/1.0.25/webcam.js"></script>
  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css'%}" rel="stylesheet">
  <link href="{% static 'css/style1.css'%}" rel="stylesheet">
  {% block style %}

  {% endblock %}
  <!-- =======================================================
  * Template Name: Restaurantly - v3.7.0
  * Template URL: https://bootstrapmade.com/restaurantly-restaurant-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>
  {% block css_block %}

    {% endblock %}
    <div class="cursor"></div>
  <!-- ======= Top Bar ======= -->
  <div id="topbar" class="d-flex align-items-center fixed-top">
    <div class="container d-flex justify-content-center justify-content-md-between">




    </div>
  </div>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-cente">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-lg-between">

      <h1 class="logo me-auto me-lg-0"><img src="{% static 'img/logo3.png'%} " alt="" class="img-fluid"><img src="{% static 'img/logo5.png'%} " alt="" class="img-fluid"></h1>
      <!-- Uncomment below if you prefer to use an image logo -->


      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>

          <li><a class="nav-link scrollto" href="{% url 'lobby' %}">Lobby</a></li>
          <li><a class="nav-link scrollto" href="{% url 'exhibition' %}">Exhibition</a></li>
          <li><a class="nav-link scrollto" href="{% url 'auditorium' %}">Auditorium</a></li>
          <li><a class="nav-link scrollto" href="#">Session Archive</a></li>

          <li><a class="nav-link scrollto" href="{% url 'clubhouse' %}">Clubhouse</a></li>
          <li><a class="nav-link scrollto" href="{% url 'selfie' %}">Selfie Booth</a></li>
          <li><a class="nav-link scrollto" href="{% url 'details' %}">Card Exchange</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'App_Login:logout' %}">Logout</a></li>


          {% else %}

          <li><a href="{% url 'App_Login:login_attempt' %}">Login</a></li>
          {% endif %}

        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->


    </div>
  </header><!-- End Header -->
  {% block content %}

    {% endblock %}


  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/aos/aos.js' %} "></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %} "></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %} "></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %} "></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %} "></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %} "></script>
  <script src="https://kit.fontawesome.com/6153aaa06f.js" crossorigin="anonymous"></script>

  <!-- Template Main JS File -->

  <script src="{% static 'js/main.js'%} "></script>
  <script src="{% static 'js/main1.js'%} "></script>
  {% block js %}

  {% endblock %}
</body>

</html>